version: '3.8'

services:
  skyl-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
        - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: skylappDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
        - app-network

networks:
  app-network:
    external: true